apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: postgres-application
  name: postgres
spec:
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  type: {{ .Values.service.type }}
