apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memo-postgres-prd
  namespace: argocd
spec:
  destination:
    namespace: memo-prd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: memo-postgres/prd
    repoURL: https://github.com/SangYunLeee/devops-manifest.git
    targetRevision: HEAD
